name: Test External Fast Forward Composite Action
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: write
  pull-requests: write
  issues: write
  
jobs:
  fast-forward:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, '/fast-forward') 
        && github.event.issue.pull_request }}
    steps:
      - uses: LuneiSolei/Fast-Forward-Blossom-Bot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_merge: true
          comment: always
          custom_command: /fast-forward
